# Generated by Django 3.2.7 on 2021-10-14 18:06

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_product_managers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(default='', max_length=50)),
                ('desc', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Model1',
        ),
        migrations.DeleteModel(
            name='Model2',
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('product', django.db.models.manager.Manager()),
            ],
        ),
    ]
